# Generated by Django 5.0.6 on 2024-08-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_user_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_date',
            field=models.DateField(blank=True, default='2001-09-11', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default='False'),
        ),
    ]
