# Generated by Django 5.0.6 on 2024-08-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='grade',
            field=models.TextField(max_length=500, verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='title',
            field=models.TextField(max_length=500, verbose_name='Название, класс, предмет'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='url',
            field=models.TextField(max_length=5000, verbose_name='Ссылка'),
        ),
    ]
